_BASE_: "faster_rcnn_R_101_FPN_ETF_pre2_10shot.yaml"


MODEL:
  META_ARCHITECTURE: "ContrastiveGeneralizedRCNN"  # 使用我们新定义的对比学习架构
  TEACHER_WEIGHT: "/root/autodl-tmp/checkpoints/voc/prior/ETFRes_pre2_10shot_lr20_adj1.0_rfs1.0_t1/model_final.pth"
  BACKBONE:
    FREEZE_AT: 3
  PROPOSAL_GENERATOR:
    FREEZE: True
  ROI_HEADS:
    NAME: "DistillMarginROIHeads"
  USE_CONTRASTIVE: True  # 启用对比学习
  CONTRASTIVE_WEIGHT: 0.001  # 对比损失的权重
  IS_DISTILL: True
LOSS:
  ADJUST_STAGE: 'distill'
SOLVER:
  BASE_LR: 0.01
# Using 0.04 is slightly better than 0.02
OUTPUT_DIR: "/root/autodl-tmp/checkpoints/voc/distill/t1"
TRAIN:
  CACHE_UPDATE_INTERVAL: 1000


